server:
  port: 8083

spring:
  application:
    name: API-GATEWAY
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path= /users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path= /hotels/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path= /ratings/**


