server:
  port: 8081

spring:
  application:
    name: Hotel-Service

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#TODO Imp Don't add Dialect again in your Microservice application
#    properties:
#      hibernate:
#        dialect: org.hibernate.cj.dialect.MySQLDialect

