
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices
  application:
    name: Rating-Service

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka